### ISSUE TITLE
Deleting a request/donation

### ISSUE THREAD

**Issue by ArmintasP** [PauliusLu/Pro-Bono#20]
Steps to recreate a bug:
1. Create a post.
2. Delete the post you've just created.
3. Press `go back one page` in your browser menu (left arrow).
4. Page freezes, a `NullReferenceException` is thrown.

My guess is that `Delete()` actually removes a data row from the table instead of changing `post.IsVisible` to `false`.

I'd like to assign myself to fix this issue, if you won't mind.

**Comment by baikauskaite** [comment]
Thank you, @ArmintasP for inspecting this. Would be great, if you could fix it.
