### ISSUE TITLE
Editing a request/donation

### ISSUE THREAD

**Issue by baikauskaite** [PauliusLu/Pro-Bono#24]
Steps to recreate the bug:

1. Create a post with your user so that you could edit it.
2. Edit the post information and save your changes.
3. Unhandled exception occurs.

![image](https://user-images.githubusercontent.com/73688133/137626823-d83e3060-2373-435b-8fbe-00eafbb3b43b.png)

**Comment by ArmintasP** [comment]
I'll fix this bug, since I also noticed it and came up with an idea how to fix it.
